### PR TITLE
resolve closing tag missing issue

### PR DESCRIPTION
**Pull request by Umangvaghela**
resolve closing tag missing issue #859

### CODE REVIEW

**Comment by Jonduglus** [comment]
@Umangvaghela 

nice ;)

**Comment by angelleye** [comment]
@Umangvaghela Ah, yes, looks like that other one I asked you about was done here...

**Comment by Umangvaghela** [comment]
@angelleye 

Hello sir,
My commit is proper or not. I tested in my local and after add PR.if my commit is fine so please merge this PR.

Thanks 
Umang vaghela

**Comment by Umangvaghela** [comment]
Hello @kcppdevelopers , @angelleye 

My PR is merged but in my name is not shown in contributor.

**Comment by angelleye** [comment]
@Umangvaghela I just added you.

**Pull request merged**
