### PR TITLE
Fix

### PR DESCRIPTION
**Pull request by Umangvaghela**
Add changes

### CODE REVIEW

**Comment by angelleye** [comment]
@Umangvaghela Am I correct that all you've done here is format the code syntax so it better matches the WordPress dev standards?

@kcppdevelopers Do you see any reason we shouldn't merge this pull request?

**Comment by Umangvaghela** [comment]
@kcppdevelopers 

Hello sir,

I have found PHP Closing tag is not matched. If we used current coding standard then it can be fine for a developer to read the code and do some stuff.

Thanks

**Comment by angelleye** [comment]
@Umangvaghela Okay, thanks again for your contributions!

**Comment by Umangvaghela** [comment]
@angelleye 

Sir if my patch is fine so can you merge this PR.Sir this directory is not for new contributor.

Thanks

Umang vaghela

**Comment by angelleye** [comment]
Yes we are going to review these one at a time and merge them accordingly.

**Comment by Umangvaghela** [comment]
@angelleye
 
Thank you sir....,:)☺

**Comment by Umangvaghela** [comment]
Hellow @angelleye. 
  
Sir when you get a chance so review it and give suggestions if I miss something.

**Comment by angelleye** [comment]
Yes, we'll be getting to it soon.  Just finishing up a few other issues on this milestone and then we'll be getting to these (in order).

**Pull request closed without merging**
