### PR TITLE
Update wc-gateway-paypal-pro-payflow-angelleye.php

### PR DESCRIPTION
**Pull request by rayflores**
added woocommerce subscriptions support

### CODE REVIEW

**Comment by charlesbeat** [comment]
Hi, I need change the SSL to TLS in curl option.

Set CURLOPT_SSLVERSION to CURL_SSLVERSION_TLSv1.

Do you have any idea?

**Comment by angelleye** [comment]
Are you getting a specific error?  Really, all you need to do is make sure that openssl and curl are running up-to-date versions, and then just letting it fall to the default protocol would work just fine.  The only time TLS doesn't work is if you're specifically setting SSL (as opposed to letting it fall to the default) or if you're running a version of openssl that is tool old.  I don't remember the exact version number, but TLS was added to openssl in 1999, so unless you're running really old server software or you're specifically setting SSLv3 you really shouldn't need to do anything.

**Comment by charlesbeat** [comment]
We turned off the SSL3 because of the "poodle ssl vulnerability". 
https://devblog.paypal.com/poodle-ssl-3-0-vulnerability/

And the paypal recommends the TLS for alternative. 
The following document referred to "update to TLS".
"Set CURLOPT_SSLVERSION to CURL_SSLVERSION_TLSv1 in your Curl options."

https://ppmts.custhelp.com/ci/fattach/get/445843/1417414724/redirect/1/session/L2F2LzEvdGltZS8xNDI2Nzc3NDgwL3NpZC83Zjh6Q0lobQ==/filename/Poodle%20SSL%203%200%20Vulnerability%20-%20Merchant%20Response%20Guide%20%28U.S.%20English%29.pdf

We got this error after turned off the SSL,

"Paypal Pro Transaction Failed (error:14094410:SSL routines:SSL3_READ_BYTES:sslv3 alert handshake failure) Order status changed from Pending Payment to Failed."

**Comment by angelleye** [comment]
Yup, I went through all of that and actually set my stuff specifically to use TLSv1 the way their documentation says to, but then I had a phone call with them (my partner manager and tech support over there) where they told me the best thing to do is let the server use the default and make sure TLS is compatible on the server.

Can you verify what version of OpenSSL and cURL that you're running?

**Comment by charlesbeat** [comment]
OpenSSl and cURL are running in that server.

**Comment by angelleye** [comment]
What versions, though?

**Comment by charlesbeat** [comment]
OpenSSL 1.0.1e-fips 11 Feb 2013

**Comment by charlesbeat** [comment]
Now I am getting the following error while checkout process in sandbox.

"An error occurred, please try again or try an alternate form of payment."

**Comment by angelleye** [comment]
Where are you seeing that error?  Is there a code associated with it?

*Andrew K. Angell*
www.angelleye.com
<http://www.angelleye.com/?utm_source=email&utm_medium=signature&utm_campaign=email_signature>
Office:  816.256.3419
Skype: angelleye

**Pull request closed without merging**
