### PR TITLE
Added confirm on capture and update order total amount without save o…

### PR DESCRIPTION
**Pull request by gine**
The action to capture the order is the most important action in the authorize/capture flow. So i have added to that action a js confirm that ask if the amount is correct.

To do that i need to have the value in "total order" field in the table "angelleye_order_action_table" updated each woocommerce order operation otherwise i show a bad value.

So i have added an observer to update this value at each operation on the div woocommerce-order-items.

### CODE REVIEW

**Comment by angelleye** [comment]
@kcppdevelopers Please review and merge accordingly.

**Comment by gine** [comment]
work well with refund but maybe there is a problem with discount. tomorrow I will do a better test.

@angelleye you are welcome

**Comment by gine** [comment]
@angelleye i confirm that it works with discount too. In the last commit have fixed only the amount format:
FROM amount  + currency_symbol TO currency_symbol + amount

**Comment by gine** [comment]
Done

**Pull request merged**
