### PR TITLE
Add composer support

### PR DESCRIPTION
**Pull request by strarsis**
This PR adds composer files (and adds `vendor/` to `.gitignore`).
This allows installing this plugin using `composer`, e.g. directly from this GitHub repository.

### CODE REVIEW

**Comment by strarsis** [comment]
For installing this plugin without a `composer.json`, 
use this in your own `composer.json`:
```json
  "repositories": [
    {
      "type": "package",
      "package": {
        "type": "wordpress-plugin",
        "name": "angelleye/paypal-woocommerce",
        "version": "2.1.9",
        "dist": {
          "url": "https://github.com/angelleye/paypal-woocommerce/archive/v2.1.9.zip",
          "type": "zip"
        },
        "source": {
          "url": "https://github.com/angelleye/paypal-woocommerce",
          "type": "vcs",
          "reference": "2.1.9"
        }
      }
    }
  ],

  "require": {
    "angelleye/paypal-woocommerce": "2.1.9"
  }
````

**Comment by matgargano** [comment]
can we get this merged?

**Comment by iMansoorAliKhan** [comment]
Hi @strarsis  Thanks for the contribution we will review that and get this merged soon.
Thanks!
Mansoor


*Mansoor Khan*
Angell EYE Customer Support Specialist
[www.angelleye.com](https://www.angelleye.com) | [Join Our Newsletter](https://www.angelleye.com/newsletter-signup/?utm_source=email&utm_medium=signature&utm_campaign=email_signature)
[Subscribe to Our YouTube Channel](https://www.youtube.com/user/angelleyeconsulting) | [Like Our Facebook Page](https://facebook.com/angelleyeconsulting/)

**Comment by angelleye** [comment]
@deepakmaurya Any particular reason we have never merged this?

**Pull request merged**
