### PR TITLE
PFW-356

### PR DESCRIPTION
**Pull request by kcppdevelopers**

### CODE REVIEW

**Comment by sagitaire123** [comment]
There's a problem with this new version, on payment section of woocommerce there's different Installed payment methods which are listed and can be sorted to control their display order on the frontend, for PayPal we can't sort it, raise or lower it, it's not working, it always remains at the bottom of the list on the checkout page.

**Comment by iMansoorAliKhan** [comment]
@sagitaire123 , Please follow your other ticket thread and its always best to submit a seperate ticket for any issues you see using our plugin.

Thanks!

**Comment by blackdigerati** [comment]
Same issue .. please fix its hurting conversion

**Comment by iMansoorAliKhan** [comment]
@blackdigerati  We have this adjusted in our backlog and will be included in our next update which is going to be available in a couple of weeks.

We appreciate you patience.
Thanks!

**Comment by blackdigerati** [comment]
There is no patience when conversion is being affected.. I have downgraded

**Comment by iMansoorAliKhan** [comment]
I can understand , and its good to use 1.5.4 version . We are trying out best to get this release asap. It wont take long.

Thanks!

**Pull request merged**
