### PR TITLE
Upgrade PayPal PHP SDK to version 1.6.4

### PR DESCRIPTION
**Pull request by mjaschen**
The PayPal WooCommerce Plugin comes bundled with the PayPal PHP SDK version 1.5.1. The PayPal PHP SDK itself is at version 1.6.4 currently.

Since January 2016 the [Sandbox API-endpoints can be reached via TLS 1.2 connections only](https://www.paypal-knowledge.com/infocenter/index?page=content&id=FAQ1914&expand=true&locale=en_US). The curl option `CURLOPT_SSLVERSION` in PayPal's PHP SDK  was changed from `1` to `6` in version 1.6.4 to comply with the new requirements.

With the currently included PayPal PHP SDK using the Sandbox API-endpoint leads to errors in the checkout process (at least with *PayPal Plus*) as no connection to the endpoint can be initiated.

I've updated the PayPal PHP SDK to 1.6.4 successfully on my installation; the connection errors are gone.

I've attached a pull request but did not run any tests as there's no test suite available for this WordPress plugin.

If upgrading the whole SDK is not an option for you, you maybe want to change the value of `CURLOPT_SSLVERSION` to `6` in `PayPal\Core\PayPalHttpConfig` as a quick fix.

### CODE REVIEW

**Comment by angelleye** [comment]
Ah, yes, thanks for pointing this out.  Most of the API calls in our plugin use our own PayPal SDK instead of theirs.  I didn't realize their's was setting that value to a 1.  

The best way to handle it is to make sure your server software stack is updated.  Then you don't need to set CURLOPT_SSLVERSION at all.  The server would fallback to the correct version whenever necessary.

For more info on that you can check [this post about POODLE](https://www.angelleye.com/paypal-ssl-error-poodle-vulnerability/).

I will have our developer take a look and probably go ahead and merge in this change.  Thanks for the feedback!

**Comment by angelleye** [comment]
@kcppdevelopers Please take a look at this and merge the updated SDK if all looks good.

**Comment by mjaschen** [comment]
> The best way to handle it is to make sure your server software stack is updated. Then you don't need to set CURLOPT_SSLVERSION at all. The server would fallback to the correct version whenever necessary.

Correct, as long as I've control over the server's configuratoin. Unfortunately the error occurred on an customer's server - where the sysops tasks are not my area of responsibility. I've reported this issue to the server's administrator too.

Best regards

Marcus

**Comment by angelleye** [comment]
@kcppdevelopers Did you pull in @mjaschen's changes or did you redo your own changes?

**Comment by kcppdevelopers** [comment]
I have download latest version of PayPal rest API and push my own changes.

**Comment by angelleye** [comment]
@kcppdevelopers Did you do anything differently than what he did?  Want to make sure we merge his changes if that's what we wound up using anyway so he gets the contribution credit.  :)

**Comment by kcppdevelopers** [comment]
it's seems everything is similar, I merge the updated SDK.

**Pull request merged**
